version: "3.3"

services:
    database:
        container_name: database
        hostname: database
        build: database
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 5432:5432
        volumes:
            - ./db_data:/var/lib/postgresql/data
        networks:
            - database_network

    api:
        container_name: api
        hostname: api
        build: api
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "81:8080"
        depends_on:
            - database
        networks:
            - database_network

networks:
    database_network:
        driver: bridge
